/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthedProposalsIndexRouteImport } from './routes/_authed/proposals/index'
import { Route as AuthedProposalsNewRouteImport } from './routes/_authed/proposals/new'
import { Route as AuthedProposalsProposalIdRouteImport } from './routes/_authed/proposals/$proposalId'
import { Route as AuthedDemoRfpAgentRouteImport } from './routes/_authed/demo/rfp-agent'

const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedProposalsIndexRoute = AuthedProposalsIndexRouteImport.update({
  id: '/proposals/',
  path: '/proposals/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedProposalsNewRoute = AuthedProposalsNewRouteImport.update({
  id: '/proposals/new',
  path: '/proposals/new',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedProposalsProposalIdRoute =
  AuthedProposalsProposalIdRouteImport.update({
    id: '/proposals/$proposalId',
    path: '/proposals/$proposalId',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedDemoRfpAgentRoute = AuthedDemoRfpAgentRouteImport.update({
  id: '/demo/rfp-agent',
  path: '/demo/rfp-agent',
  getParentRoute: () => AuthedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/demo/rfp-agent': typeof AuthedDemoRfpAgentRoute
  '/proposals/$proposalId': typeof AuthedProposalsProposalIdRoute
  '/proposals/new': typeof AuthedProposalsNewRoute
  '/proposals/': typeof AuthedProposalsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/demo/rfp-agent': typeof AuthedDemoRfpAgentRoute
  '/proposals/$proposalId': typeof AuthedProposalsProposalIdRoute
  '/proposals/new': typeof AuthedProposalsNewRoute
  '/proposals': typeof AuthedProposalsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/_authed/demo/rfp-agent': typeof AuthedDemoRfpAgentRoute
  '/_authed/proposals/$proposalId': typeof AuthedProposalsProposalIdRoute
  '/_authed/proposals/new': typeof AuthedProposalsNewRoute
  '/_authed/proposals/': typeof AuthedProposalsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sign-in'
    | '/sign-up'
    | '/demo/rfp-agent'
    | '/proposals/$proposalId'
    | '/proposals/new'
    | '/proposals/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sign-in'
    | '/sign-up'
    | '/demo/rfp-agent'
    | '/proposals/$proposalId'
    | '/proposals/new'
    | '/proposals'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/sign-in'
    | '/sign-up'
    | '/_authed/demo/rfp-agent'
    | '/_authed/proposals/$proposalId'
    | '/_authed/proposals/new'
    | '/_authed/proposals/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/proposals/': {
      id: '/_authed/proposals/'
      path: '/proposals'
      fullPath: '/proposals/'
      preLoaderRoute: typeof AuthedProposalsIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/proposals/new': {
      id: '/_authed/proposals/new'
      path: '/proposals/new'
      fullPath: '/proposals/new'
      preLoaderRoute: typeof AuthedProposalsNewRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/proposals/$proposalId': {
      id: '/_authed/proposals/$proposalId'
      path: '/proposals/$proposalId'
      fullPath: '/proposals/$proposalId'
      preLoaderRoute: typeof AuthedProposalsProposalIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/demo/rfp-agent': {
      id: '/_authed/demo/rfp-agent'
      path: '/demo/rfp-agent'
      fullPath: '/demo/rfp-agent'
      preLoaderRoute: typeof AuthedDemoRfpAgentRouteImport
      parentRoute: typeof AuthedRoute
    }
  }
}

interface AuthedRouteChildren {
  AuthedDemoRfpAgentRoute: typeof AuthedDemoRfpAgentRoute
  AuthedProposalsProposalIdRoute: typeof AuthedProposalsProposalIdRoute
  AuthedProposalsNewRoute: typeof AuthedProposalsNewRoute
  AuthedProposalsIndexRoute: typeof AuthedProposalsIndexRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedDemoRfpAgentRoute: AuthedDemoRfpAgentRoute,
  AuthedProposalsProposalIdRoute: AuthedProposalsProposalIdRoute,
  AuthedProposalsNewRoute: AuthedProposalsNewRoute,
  AuthedProposalsIndexRoute: AuthedProposalsIndexRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
